jwt:
    signkey: testaaaa
server:
    port: 8080
spring:
    application:
        name: auth-server
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        name: defaultDataSource
        password: 123456
        url: jdbc:mysql://localhost:3306/sso?serverTimezone=UTC
        username: root
    session:
        store-type: redis
    thymeleaf:
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        mode: HTML5
        prefix: classpath:/templates/
        suffix: .html
